### ISSUE TITLE
bug: incorrect hours on dashboard for midnight shifts

### ISSUE THREAD

**Issue by QiLinXue** [volunteeringpeel/volunteeringpeel#111] opened 2019-07-09 23:40 UTC
Steps to reproduce:
- Create shift that goes to midnight (12:00 AM)
- Sign up for the shift
- Go to dashboard and the #of hours will be an extra 12.

**Comment by RetroCraft** [comment] 2019-07-10 00:44
Turns out this was caused by user error.

Will create a patch to prevent this from happening again by validating that end_date > start_date.

Closing.

**Closed by RetroCraft** 2019-07-10 00:44 UTC
